### ISSUE TITLE
No validation on login form

### ISSUE THREAD

**Issue by Fermain** [RohitAmdahl/social_media_website#4]
The criteria requires HTML form validation to be applied to the login form.

**Comment by RohitAmdahl** [comment]
do u mean like i did in previous assignments , with java script.  also i have used in action /profile,html  is is not correct ?

**Comment by Fermain** [comment]
I didn't say anything about the action attribute, this is fine.

We discussed validation last week and I said that you should use HTML validation not JS. I provided a Youtube video on this subject.

**Comment by RohitAmdahl** [comment]
ok thanks i will watch that video to understand that part

**Comment by RohitAmdahl** [comment]
i have updated my login page and log in from Html validation

**Comment by Fermain** [comment]
As the repository owner you have the right to close issues that you have solved 😄

**Comment by RohitAmdahl** [comment]
ok I did not knew that I thought u are the owner now 😄

**Comment by Fermain** [comment]
It's your name in the URL not mine! I am your reviewer, here to help, not here to control

**Comment by RohitAmdahl** [comment]
ok
